### ISSUE TITLE
Please add os.O_TRUNC to writeFlags

### ISSUE THREAD

**Issue by richardweinberger** [cavaliercoder/grab#23]
...otherwise when the target file already exists downloading will with ErrBadLength because the existing file may have a different length.

**Comment by cavaliercoder** [comment]
This was by design, but I'm happy to rethink it. If the existing file is larger than the remote file, then it can't possibly be the same file. Therefore, grab should exit with a user-actionable error.

I've changed this now, if `Request.NoResume` is set to true, the local file will always be overwritten, except if the size exactly matches the remote file.
